title:              ME 495 - Embedded Systems in Robotics
description:        ""
url:                "http://localhost:4000"
baseurl:            /msr-site

markdown:           kramdown
permalink:          pretty